all.tex: $(VFILES)
	$(SHOW)'COQDOC -latex $(GAL)'
	$(HIDE)$(COQDOC) \
		-toc $(COQDOCFLAGS) -latex $(GAL) $(COQDOCLIBS) \
		-o $@ $(VFILES)

# Work around the LaTeX nesting limit
COQDOCFLAGS = -interpolate -utf8 -p '\usepackage{enumitem}\setlistdepth{9}\setlist[itemize,1]{label=$$\bullet$$}\setlist[itemize,2]{label=$$\bullet$$}\setlist[itemize,3]{label=$$\bullet$$}\setlist[itemize,4]{label=$$\bullet$$}\setlist[itemize,5]{label=$$\bullet$$}\setlist[itemize,6]{label=$$\bullet$$}\setlist[itemize,7]{label=$$\bullet$$}\setlist[itemize,8]{label=$$\bullet$$}\setlist[itemize,9]{label=$$\bullet$$}\renewlist{itemize}{itemize}{9}'
