(** * Symbols: Special symbols *)

(* This file defines some HTML symbols for use by the coqdoc
   preprocessor.  It is not intended to be read by anybody. *)

(** printing ->  *)
(** printing \\  *)
(** printing ==>  *)
(** printing ==>*  *)
(** printing ==>+  *)
(** printing |- #<span style="font-family: arial;">&#x22A2;</span># *)
(** printing <-  *)
(** printing <->  *)
(** printing forall  *)
(** printing exists  *)
(** printing /\  *)
(** printing \/  *)
(** printing ->> #<span style="font-family: arial;">&#8702;</span># *)
(** printing <<->> #<span style="font-family: arial;">&#8703;</span># *)
(** printing |- #<span style="font-family: arial;">&#8866;</span># *)
(** printing Gamma  *)
(** printing Gamma'  *)
(** printing Gamma''  *)
(** printing |-> #<span style="font-family: arial;">&#8614;</span># *)

(** $Date: 2016-05-26 16:17:19 -0400 (Thu, 26 May 2016) $ *)
